#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: launch <image-tag>"
  exit 1
fi

if [ -x "$(which podman)" ]; then
  CONTAINER_CMD=podman
elif [ -x "$(which docker)" ]; then
  CONTAINER_CMD=docker
else
  echo "Neither podman nor docker are installed"
  exit 1
fi

for SECRET in wcfc-apps-mongodb wcfc-apps-groups-io wcfc-apps-WCFC_TOKEN; do
  if ! echo ${CONTAINER_CMD} secret exists $SECRET; then
    echo "Please set up Podman secrets before running this pod"
    exit 1
  fi
done

mkdir -p $(pdw)/log

echo ${CONTAINER_CMD} rm -f wcfc-groups
echo ${CONTAINER_CMD} run -d --name wcfc-groups -p 9301:9301 \
  --secret=wcfc-apps-mongodb,type=env,target=MONGODB \
  --secret=wcfc-apps-groups-io,type=env,target=GROUPS_IO_API_KEY \
  --secret=wcfc-apps-WCFC_TOKEN,type=env,target=WCFC_TOKEN \
  -v $(pwd)/log:/opt/app/log \
 $1
